# Generated by Django 2.2.7 on 2019-11-26 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('locationType', models.CharField(choices=[('FO', 'Forest'), ('DS', 'Desert'), ('DU', 'Dungeon'), ('RI', 'River'), ('OC', 'Ocean')], default='FO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('playerclass', models.CharField(choices=[('KN', 'Knight'), ('WI', 'Wizard'), ('TH', 'Thief'), ('PL', 'Paladin')], default='KN', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apivm.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('messageText', models.CharField(max_length=1000)),
                ('playerFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_from', to='apivm.Player')),
                ('playerTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_to', to='apivm.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('itemType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apivm.ItemType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apivm.Player')),
            ],
        ),
    ]
