# Generated by Django 2.2.7 on 2019-11-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apivm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='author',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='text',
        ),
        migrations.RemoveField(
            model_name='player',
            name='title',
        ),
    ]
